name: flutter_template
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.1.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  collection: ^1.18.0
  connectivity_plus: ^6.0.1
  cupertino_icons: ^1.0.6
  device_info_plus: ^10.0.1
  envied: ^0.5.4+1
  equatable: ^2.0.5
  flex_color_scheme: ^7.3.1
  flextras: ^1.0.0
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.1.10+1
  flutter_layout_grid: ^2.0.6
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  flutter_web_plugins:
    sdk: flutter
  gap: ^3.0.1
  go_router: ^13.2.2
  growthbook_sdk_flutter: ^3.2.0+0
  http: ^1.2.1
  intl: ^0.18.1
  intl_utils: ^2.8.7
  logging: ^1.2.0
  package_info_plus: ^6.0.0
  responsive_builder: ^0.7.0
  riverpod: ^2.5.1
  url_launcher: ^6.2.5
  version: ^3.0.2

dev_dependencies:
  build_runner: ^2.4.9
  envied_generator: ^0.5.4+1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_intl:
  enabled: true
  main_locale: en
  arb_dir: lib/app/l10n
  output_dir: lib/app/l10n/generated
